web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://edrox.net'
  ports:
    - '80:9080'
    - '443:9443'
    - '22:9022'
  volumes:
    - '/mnt/cache/appdata/gitlab-ce/config:/etc/gitlab'
    - '/mnt/cache/appdata/gitlab-ce/data:/var/log/gitlab'
    - '/mnt/cache/appdata/gitlab-ce/log:/var/opt/gitlab'
